-- Create jobs table
create table public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text not null,
  description text not null,
  skills text[] not null,
  budget text not null,
  duration text not null,
  posted_date date not null,
  contact_email text not null,
  location text not null,
  experience_level text not null,
  requirements text[] not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.jobs enable row level security;

-- Create policy to allow public read access
create policy "Allow public read access"
  on public.jobs
  for select
  using (true);

-- Create policy to allow authenticated users to insert (for future use)
create policy "Allow authenticated users to insert"
  on public.jobs
  for insert
  with check (auth.role() = 'authenticated');

-- Seed data
insert into public.jobs (
  title, company, description, skills, budget, duration, posted_date, contact_email, location, experience_level, requirements
) values
  (
    'Build E-commerce Website',
    'Local Boutique',
    'Looking for a developer to create a modern e-commerce website with payment integration and inventory management.',
    ARRAY['Web Development', 'Programming', 'UI/UX Design'],
    '$2,000 - $3,500',
    '4-6 weeks',
    '2024-01-15',
    'contact@localboutique.com',
    'Remote',
    'Mid',
    ARRAY['Experience with e-commerce platforms', 'Payment gateway integration details']
  ),
  (
    'Social Media Graphics Package',
    'Fitness Studio',
    'Need a complete social media graphics package including Instagram posts, stories, and promotional materials.',
    ARRAY['Graphic Design', 'Logo Design', 'Animation'],
    '$800 - $1,200',
    '2-3 weeks',
    '2024-01-18',
    'marketing@fitnessstudio.com',
    'Hybrid',
    'Entry',
    ARRAY['Portfolio required', 'Adobe Creative Suite expertise']
  ),
  (
    '3D Product Visualization',
    'Tech Startup',
    'Create 3D models and animations for our new product line to use in marketing materials.',
    ARRAY['3D Modeling', 'Blender', 'Animation'],
    '$1,500 - $2,500',
    '3-4 weeks',
    '2024-01-20',
    'creative@techstartup.com',
    'Remote',
    'Mid',
    ARRAY['Blender proficiency', 'Previous product viz experience']
  ),
  (
    'Indie Game Development',
    'Indie Studio',
    'Join our team to develop a 2D platformer game. Need someone skilled in game mechanics and level design.',
    ARRAY['Game Design', 'Programming', 'Animation'],
    '$3,000 - $5,000',
    '8-10 weeks',
    '2024-01-22',
    'dev@indiestudio.com',
    'On-site',
    'Senior',
    ARRAY['Unity or Godot experience', 'Shipped at least one game']
  ),
  (
    'Mobile App UI/UX Design',
    'HealthTech Inc',
    'Design user interface for a mental health tracking mobile app. Need clean, accessible design with user-friendly navigation.',
    ARRAY['UI/UX Design', 'Mobile Design', 'Figma'],
    '$1,800 - $2,800',
    '5-6 weeks',
    '2024-01-25',
    'design@healthtech.com',
    'Remote',
    'Mid',
    ARRAY['Portfolio with mobile app designs', 'Experience with healthcare apps preferred', 'Figma proficiency required']
  ),
  (
    'Content Writing for Tech Blog',
    'DevTools Pro',
    'Write technical articles about software development tools and best practices. Need someone who can explain complex topics clearly.',
    ARRAY['Content Writing', 'Technical Writing', 'SEO'],
    '$600 - $1,000',
    '4 weeks',
    '2024-01-26',
    'content@devtools.com',
    'Remote',
    'Entry',
    ARRAY['Strong English writing skills', 'Basic programming knowledge', 'SEO writing experience']
  ),
  (
    'Data Analysis & Visualization',
    'Green Energy Solutions',
    'Analyze renewable energy data and create interactive dashboards for stakeholder presentations.',
    ARRAY['Data Analysis', 'Python', 'Tableau'],
    '$2,200 - $3,200',
    '6-8 weeks',
    '2024-01-28',
    'analytics@greenenergy.com',
    'Hybrid',
    'Mid',
    ARRAY['Python/R proficiency', 'Experience with Tableau or Power BI', 'Statistics background preferred']
  ),
  (
    'Instagram Marketing Campaign',
    'Artisan Coffee Co',
    'Create and manage Instagram marketing campaign including content creation, posting schedule, and engagement strategies.',
    ARRAY['Social Media Marketing', 'Content Creation', 'Photography'],
    '$900 - $1,400',
    '6 weeks',
    '2024-01-29',
    'marketing@artisancoffee.com',
    'Remote',
    'Entry',
    ARRAY['Instagram marketing experience', 'Content creation skills', 'Basic photography knowledge']
  ),
  (
    'WordPress Website Redesign',
    'Legal Partners LLC',
    'Complete redesign of law firm website using WordPress. Need professional, trustworthy design that converts visitors to clients.',
    ARRAY['WordPress', 'Web Design', 'SEO'],
    '$1,500 - $2,500',
    '4-5 weeks',
    '2024-01-30',
    'admin@legalpartners.com',
    'Remote',
    'Mid',
    ARRAY['WordPress expertise', 'Legal industry experience preferred', 'SEO knowledge required']
  ),
  (
    'Video Editing for YouTube Channel',
    'EduTech Academy',
    'Edit educational videos for YouTube channel including intro/outro, transitions, graphics, and audio optimization.',
    ARRAY['Video Editing', 'Motion Graphics', 'Audio Editing'],
    '$1,200 - $2,000',
    'Ongoing',
    '2024-02-01',
    'video@edutech.com',
    'Remote',
    'Entry',
    ARRAY['Adobe Premiere/Final Cut Pro', 'Motion graphics skills', 'YouTube optimization knowledge']
  ),
  (
    'Backend API Development',
    'FinTech Startup',
    'Build secure REST API for fintech application with payment processing, user authentication, and transaction handling.',
    ARRAY['Backend Development', 'Node.js', 'Database Design'],
    '$4,000 - $6,000',
    '8-12 weeks',
    '2024-02-02',
    'dev@fintechstartup.com',
    'Remote',
    'Senior',
    ARRAY['5+ years backend experience', 'Financial services knowledge', 'Security best practices', 'MongoDB/PostgreSQL']
  ),
  (
    'Brand Identity Package',
    'Sustainable Fashion Brand',
    'Create complete brand identity including logo, color palette, typography, and brand guidelines for eco-friendly clothing line.',
    ARRAY['Brand Design', 'Logo Design', 'Graphic Design'],
    '$1,800 - $3,000',
    '6-8 weeks',
    '2024-02-03',
    'branding@sustainablefashion.com',
    'Remote',
    'Mid',
    ARRAY['Brand identity portfolio', 'Sustainability sector experience preferred', 'Adobe Creative Suite proficiency']
  ),
  (
    'React Native Mobile App',
    'Food Delivery Service',
    'Develop cross-platform mobile app for food delivery service with real-time tracking and payment integration.',
    ARRAY['React Native', 'Mobile Development', 'API Integration'],
    '$5,000 - $8,000',
    '10-14 weeks',
    '2024-02-05',
    'mobile@fooddelivery.com',
    'Hybrid',
    'Senior',
    ARRAY['React Native expertise', 'Payment gateway integration', 'Real-time features experience', 'App store deployment']
  ),
  (
    'Podcast Production & Editing',
    'Business Insights Podcast',
    'Full podcast production including recording setup, audio editing, show notes creation, and distribution management.',
    ARRAY['Audio Production', 'Podcast Editing', 'Content Creation'],
    '$800 - $1,200',
    'Ongoing',
    '2024-02-06',
    'podcast@businessinsights.com',
    'Remote',
    'Entry',
    ARRAY['Audio editing software proficiency', 'Podcast production experience', 'Content writing skills']
  ),
  (
    'Cybersecurity Assessment',
    'Regional Hospital Network',
    'Conduct comprehensive cybersecurity assessment and provide recommendations for healthcare data protection compliance.',
    ARRAY['Cybersecurity', 'Risk Assessment', 'Compliance'],
    '$3,500 - $5,500',
    '6-8 weeks',
    '2024-02-08',
    'security@regionalhospital.com',
    'On-site',
    'Senior',
    ARRAY['CISSP/CEH certification preferred', 'Healthcare compliance knowledge', 'Penetration testing experience', 'HIPAA familiarity']
  ),
  (
    'Mobile App UI/UX Design',
    'FinTech Startup',
    'Design intuitive user interface and experience for a new personal finance mobile application targeting college students.',
    ARRAY['UI/UX Design', 'Mobile Design', 'Figma', 'User Research'],
    '$1,200 - $2,000',
    '3-4 weeks',
    '2024-02-10',
    'design@fintechstartup.com',
    'Remote',
    'Entry',
    ARRAY['Portfolio showcasing mobile app designs', 'Experience with design systems', 'Understanding of accessibility principles']
  ),
  (
    'Content Writing & SEO',
    'Digital Marketing Agency',
    'Create engaging blog content and optimize for search engines for multiple client websites in various industries.',
    ARRAY['Content Writing', 'SEO', 'Research', 'Digital Marketing'],
    '$600 - $1,000',
    'Ongoing',
    '2024-02-12',
    'content@digitalagency.com',
    'Remote',
    'Entry',
    ARRAY['Strong writing portfolio', 'Basic SEO knowledge', 'Research skills', 'Ability to adapt voice and tone']
  ),
  (
    'Database Migration Project',
    'Manufacturing Company',
    'Migrate legacy database system to modern cloud-based solution with minimal downtime and data integrity preservation.',
    ARRAY['Database Management', 'Cloud Computing', 'Data Migration', 'SQL'],
    '$4,000 - $6,000',
    '8-10 weeks',
    '2024-02-14',
    'it@manufacturing.com',
    'Hybrid',
    'Mid',
    ARRAY['Experience with database migrations', 'Cloud platform knowledge (AWS/Azure)', 'Data backup and recovery expertise']
  ),
  (
    'Video Production & Editing',
    'Educational Non-Profit',
    'Produce and edit educational video content for online learning platform, including animations and interactive elements.',
    ARRAY['Video Editing', 'Animation', 'Storytelling', 'Adobe Premiere'],
    '$1,500 - $2,500',
    '4-5 weeks',
    '2024-02-16',
    'media@educationalnpo.org',
    'Remote',
    'Mid',
    ARRAY['Portfolio of educational content', 'Animation skills', 'Understanding of learning principles']
  ),
  (
    'AI Chatbot Development',
    'Customer Service Solutions',
    'Develop intelligent chatbot for customer support using natural language processing and machine learning.',
    ARRAY['AI/ML', 'Python', 'Natural Language Processing', 'API Development'],
    '$3,000 - $4,500',
    '6-8 weeks',
    '2024-02-18',
    'tech@customersolutions.com',
    'Remote',
    'Mid',
    ARRAY['Experience with NLP libraries', 'Machine learning background', 'API integration skills']
  ),
  (
    'Brand Identity Package',
    'Local Restaurant Chain',
    'Create complete brand identity including logo, color palette, typography, and brand guidelines for expanding restaurant chain.',
    ARRAY['Brand Design', 'Logo Design', 'Typography', 'Brand Strategy'],
    '$2,000 - $3,000',
    '4-6 weeks',
    '2024-02-20',
    'marketing@restaurantchain.com',
    'Hybrid',
    'Mid',
    ARRAY['Brand design portfolio', 'Understanding of food industry', 'Print and digital design experience']
  ),
  (
    'WordPress Plugin Development',
    'WordPress Agency',
    'Develop custom WordPress plugin for e-commerce functionality with advanced filtering and search capabilities.',
    ARRAY['WordPress', 'PHP', 'JavaScript', 'Plugin Development'],
    '$1,800 - $2,800',
    '5-6 weeks',
    '2024-02-22',
    'dev@wordpressagency.com',
    'Remote',
    'Mid',
    ARRAY['WordPress plugin development experience', 'PHP proficiency', 'E-commerce knowledge']
  ),
  (
    'Social Media Strategy',
    'Tech Conference',
    'Develop and execute comprehensive social media strategy for annual technology conference, including content creation and community management.',
    ARRAY['Social Media Marketing', 'Content Creation', 'Community Management', 'Analytics'],
    '$1,000 - $1,800',
    '8-10 weeks',
    '2024-02-24',
    'marketing@techconference.com',
    'Remote',
    'Entry',
    ARRAY['Social media portfolio', 'Understanding of tech industry', 'Content creation skills']
  ),
  (
    'Data Visualization Dashboard',
    'Healthcare Analytics',
    'Create interactive data visualization dashboard for hospital metrics using modern charting libraries and real-time data.',
    ARRAY['Data Visualization', 'JavaScript', 'D3.js', 'Dashboard Design'],
    '$2,500 - $4,000',
    '6-7 weeks',
    '2024-02-26',
    'analytics@healthcaredata.com',
    'Remote',
    'Mid',
    ARRAY['Data visualization portfolio', 'Experience with charting libraries', 'Healthcare data understanding']
  ),
  (
    'Podcast Production',
    'Business Podcast Network',
    'Handle complete podcast production including editing, mixing, and post-production for weekly business interview series.',
    ARRAY['Audio Editing', 'Podcast Production', 'Sound Design', 'Audacity/Pro Tools'],
    '$800 - $1,200',
    'Ongoing',
    '2024-02-28',
    'production@businesspodcast.com',
    'Remote',
    'Entry',
    ARRAY['Audio editing portfolio', 'Podcast production experience', 'Quick turnaround capability']
  );
